import test from 'node:test';
import assert from 'node:assert/strict';
import {assess,validateParcel,validateBackup,daysUntil,escapeHtml,SOURCES,POLICIES} from '../src/domain.js';
const p=(overrides={})=>validateParcel({id:'test-1',name:'테스트 농지',lat:36.5,lng:127.5,acquisition:'purchase',use:'self',facility:'none',mismatch:'no',notice:'no',role:'owner',ownership:'sole',...overrides});
test('직접경작 완성 입력은 기본 점검이며 법적 승인이 아니다',()=>{const a=assess(p());assert.equal(a.status,'basic');assert.equal(a.known,5);assert(a.checks.some(c=>c.id==='evidence'));assert(!('riskScore'in a));});
test('정보 부족을 낮은 위험으로 표시하지 않는다',()=>assert.equal(assess(p({use:'unknown',mismatch:'unknown'})).status,'missing'));
test('휴경은 사유 확인 항목, 자동 위법 판정이 아니다',()=>{const a=assess(p({use:'fallow'}));assert.equal(a.status,'priority');assert(a.checks.find(c=>c.id==='fallow').action.includes('원인'));});
test('상속을 한 필지 면적만으로 합법 판정하지 않는다',()=>{const a=assess(p({acquisition:'inheritance',area:9000,use:'leased',leaseReason:'inheritance',contract:'written'}));assert.equal(a.status,'review');assert(a.checks.find(c=>c.id==='inheritance').action.includes('전체'));});
test('증여를 상속 예외로 판정하지 않는다',()=>assert(!assess(p({acquisition:'gift'})).checks.some(c=>c.id==='inheritance')));
test('고령농 예외 입력도 확정이 아니다',()=>assert(assess(p({use:'leased',leaseReason:'elder'})).checks.find(c=>c.id==='exception').reason.includes('확정은 아닙니다')));
test('가족 경작을 자동 불법임대로 취급하지 않는다',()=>assert(!assess(p({use:'family'})).checks.some(c=>c.id==='lease')));
test('경매·공유지분만으로 투기 점수 부여하지 않는다',()=>{const a=assess(p({acquisition:'auction',ownership:'shared'}));assert.equal(a.status,'review');assert(a.checks.find(c=>c.id==='shared').reason.includes('자동으로'));});
test('행정정보 불일치는 사용자 보고임을 표시한다',()=>assert(assess(p({mismatch:'yes'})).checks.find(c=>c.id==='mismatch').reason.includes('사용자')));
test('허가 미확인 시설은 우선 확인',()=>assert.equal(assess(p({facility:'unverified'})).status,'priority'));
test('통지 기한은 KST 자정 기준',()=>{assert.equal(daysUntil('2026-10-06',new Date('2026-10-05T14:59:00Z')),1);assert.equal(daysUntil('2026-10-06',new Date('2026-10-05T15:01:00Z')),0);});
test('경과 기한과 잘못된 날짜 구분',()=>{assert.equal(daysUntil('2026-10-04',new Date('2026-10-05T00:00:00Z')),-1);assert.equal(daysUntil('x'),null);});
test('체크 완료가 점검 상태를 낮추지 않는다',()=>assert.equal(assess(p({use:'fallow',done:['fallow']})).status,'priority'));
test('좌표가 없어도 자료 관리 가능',()=>assert.equal(p({lat:'',lng:''}).lat,null));
test('잘못된 좌표·면적·PNU는 저장 거부',()=>{for(const bad of [{lat:91},{lng:181},{lat:'abc'},{lat:36,lng:''},{area:0},{area:-1},{pnu:'123'}])assert.throws(()=>p(bad));});
test('PNU는 19자리 문자열을 유지',()=>assert.equal(p({pnu:'0012345678901234567'}).pnu,'0012345678901234567'));
test('존재하지 않는 날짜 거부',()=>assert.throws(()=>p({acquiredAt:'2026-02-30'})));
test('저장 ID·이름 확인',()=>{assert.throws(()=>p({id:'<script>'}));assert.throws(()=>p({name:''}));});
test('사용자 데이터는 HTML escape',()=>assert.equal(escapeHtml('<img onerror="x">&\''),'&lt;img onerror=&quot;x&quot;&gt;&amp;&#39;'));
test('미등록 선택값은 unknown',()=>assert.equal(p({use:'automatically-legal'}).use,'unknown'));
test('증빙 포함 백업 기본 형식',()=>assert.equal(validateBackup({schema:'farmland-policy-map/v1',parcels:[p()],evidence:[]}).parcels.length,1));
test('다른 앱의 파일·중복 ID 거부',()=>{assert.throws(()=>validateBackup({schema:'x',parcels:[],evidence:[]}));assert.throws(()=>validateBackup({schema:'farmland-policy-map/v1',parcels:[p(),p()],evidence:[]}));});
test('증빙의 잘못된 연결·실행 가능 첨부 거부',()=>{for(const data of ['data:text/html;base64,PHNjcmlwdD4=','data:image/svg+xml;base64,AAAA','javascript:alert(1)'])assert.throws(()=>validateBackup({schema:'farmland-policy-map/v1',parcels:[p()],evidence:[{id:'ev1',parcelId:'test-1',data}]}));assert.throws(()=>validateBackup({schema:'farmland-policy-map/v1',parcels:[p()],evidence:[{id:'ev1',parcelId:'missing',data:''}]}));});
test('검증된 형식의 이미지 백업 허용',()=>assert.equal(validateBackup({schema:'farmland-policy-map/v1',parcels:[p()],evidence:[{id:'ev1',parcelId:'test-1',data:'data:image/png;base64,AAAA'}]}).evidence.length,1));
test('정책·진단 결과 모두 공식 출처가 있다',()=>{for(const policy of POLICIES)assert(SOURCES[policy.source]?.url.startsWith('https://'));for(const value of ['self','leased','fallow','family','unknown'])for(const c of assess(p({use:value,acquisition:'inheritance',notice:'yes',mismatch:'yes',facility:'unverified'})).checks)assert(SOURCES[c.source]);});
