/** Auditable one-time source migration. Keeps the existing IndexedDB schema unchanged. */
import {readFile,writeFile} from 'node:fs/promises';
let app=await readFile('src/app.js','utf8');
if(app.includes("from './naver-map.js'")){console.log('Naver source migration already applied.');process.exit(0);}
function replace(from,to){if(!app.includes(from))throw Error('Missing migration anchor: '+from.slice(0,100));app=app.replace(from,to);}
function fn(name,source){const re=new RegExp('^(?:async )?function '+name+'\\([^\\n]*$','m');if(!re.test(app))throw Error('Missing function '+name);app=app.replace(re,()=>source);}
app="import {NaverMapController,searchAddress} from './naver-map.js';\nimport {DEFAULT_NAVER_KEY,inBounds,sortRows,latestGate} from './map-utils.js';\n"+app;
replace("lastSearch:0};","lastSearch:0,bounds:null,holdRows:false,heldRows:[],hidden:new Set(),searchGate:latestGate()};");
replace("let config={vworldKey:''","let config={naverKeyId:DEFAULT_NAVER_KEY,vworldKey:''");
replace('state.view=v;','state.view=v;document.body.dataset.view=v;');
replace("lat:point?.lat??null,lng:point?.lng??null,source:'사용자 입력'","lat:point?.lat??null,lng:point?.lng??null,address:point?.address||'',source:point?.address?'네이버 주소 확인 · 경계/소유 미확인':'사용자 입력'");
replace("config={vworldKey:key","config={naverKeyId:String(f.get('naverKeyId')||'').trim()||DEFAULT_NAVER_KEY,vworldKey:key");
replace('<h3>공간정보 API 연결</h3>','<h3>네이버 지도 · 공간정보 연결</h3><p>돌봄한눈과 같은 네이버 지도 브라우저 ID를 기본 사용합니다. 현재 Origin이 네이버 Maps Application에 허용되어 있어야 합니다. Client Secret은 입력하지 마세요.</p>');
replace('<form id="config-form"><label>VWorld','<form id="config-form"><label>네이버 Maps Key ID<input name="naverKeyId" value="${esc(config.naverKeyId)}" autocomplete="off"></label><p class="small-note">네이버 키를 바꾸면 저장 후 새로고침하세요. 농지 데이터는 유지됩니다.</p><label>VWorld');
replace("$('#config-form').onsubmit=e=>{e.preventDefault();","$('#config-form').onsubmit=e=>{e.preventDefault();const oldNaver=config.naverKeyId;");
replace("setupOverlays();closeModal();toast(key?","setupOverlays();closeModal();if(oldNaver!==config.naverKeyId){location.reload();return;}toast(key?");
replace('Leaflet 파일은 unpkg, 배경지도는 OpenStreetMap에서 받습니다.','배경지도·위성지도·주소 검색은 네이버 Maps에서 받습니다. 지도 중심과 배율은 같은 탭의 세션 저장소에 보관합니다.');
replace('IP·참조 도메인·조회 타일 좌표가 제공자에게 전달될 수 있습니다.','IP·참조 도메인·조회 위치와 사용자가 제출한 주소 검색어가 네이버에 전달될 수 있습니다.');
replace('현재 위치로 이동했습니다. 위치는 저장되지 않았습니다.','현재 위치로 이동했습니다. 농지로 등록하지는 않았습니다.');
fn('filtered',`function filtered(){const v=$('#filter').value;const rows=sortRows(state.parcels.filter(p=>v==='all'||assess(p).status===v),$('#map-sort').value,assess);if(state.holdRows)return state.heldRows.map(id=>rows.find(p=>p.id===id)).filter(Boolean);return $('#scope').value==='viewport'&&state.bounds?rows.filter(p=>p.lat===null||inBounds(p,state.bounds)):rows;}`);
fn('renderList',`function renderList(){const host=$('#parcel-list'),top=host.scrollTop,rows=filtered();host.innerHTML=rows.length?rows.map((p,i)=>'<article class="parcel-row"><input type="checkbox" data-map-check="'+esc(p.id)+'" '+(!state.hidden.has(p.id)?'checked':'')+' aria-label="'+esc(p.name)+' 지도 표시"><button class="parcel-card '+(p.id===state.selected?'selected':'')+'" data-action="select" data-id="'+esc(p.id)+'"><div class="card-head"><strong><span class="row-number">'+(i+1)+'</span>'+esc(p.name)+'</strong>'+badge(assess(p).status)+'</div><p>'+esc(p.address||'주소 미입력')+(p.demo?' · 가상 예시':'')+'</p><div class="card-meta"><span>'+label('use',p.use)+' · '+(p.area?num(p.area)+'㎡':'면적 미입력')+'</span><span>'+ (p.lat===null?'좌표 미입력':'위치 등록')+'</span></div></button></article>').join(''):empty(state.parcels.length?'현재 조건에 맞는 농지가 없습니다':'아직 등록된 농지가 없어요',state.parcels.length?'지도를 이동하거나 전체 농지 보기를 선택하세요.':'지도를 눌러 등록하거나 예시로 먼저 살펴보세요.','<button class="primary" data-action="add">농지 등록</button> <button class="text-btn" data-action="demo">예시 체험</button>');host.scrollTop=top;updateMapTools();}`);
fn('selectParcel',`function selectParcel(id){const p=state.parcels.find(p=>p.id===id);if(!p)return;if(!filtered().some(x=>x.id===id)){state.holdRows=false;$('#scope').value='all';}state.heldRows=filtered().map(p=>p.id);state.holdRows=true;state.selected=id;state.tab='checks';state.hidden.delete(id);showView('map');renderList();renderDetail();renderMarkers();state.map?.closePopup();state.map?.focus(id);document.querySelector('.parcel-card.selected')?.scrollIntoView({block:'nearest',behavior:'instant'});}`);
fn('initMap',`async function initMap(){try{state.map=new NaverMapController($('#map'),{onPick:point=>parcelForm(null,point),onViewport:bounds=>{if($('#auto-search').checked){state.bounds=bounds;if(!state.holdRows){renderList();renderMarkers();}}else $('#search-area').hidden=false;},onGesture:()=>{state.holdRows=false;state.selected=null;$('#detail').hidden=true;},onStatus:message=>{$('#map-status').hidden=false;$('#map-status').textContent=message;},getConfig:()=>config});await state.map.init(config.naverKeyId);state.map.onSelect=selectParcel;$('#map-status').hidden=true;renderMarkers();}catch(err){state.map=null;document.body.dataset.mapReady='false';$('#map').innerHTML='<div class="map-unavailable"><h2>네이버 지도 연결을 확인해 주세요</h2><p>'+esc(err.message)+'</p><p>Maps Application의 Web 서비스 URL에 '+esc(location.origin)+' 등록이 필요합니다. 농지·증빙 기능은 계속 사용할 수 있습니다.</p><button data-action="settings">지도 설정</button></div>';$('#map-status').hidden=true;}}`);
fn('setupOverlays',`function setupOverlays(){state.map?.updateOverlays(true);}`);
fn('renderMarkers',`function renderMarkers(){state.map?.render(filtered(),state.hidden,state.selected);updateMapTools();}`);
fn('fit',`function fit(){state.holdRows=false;$('#scope').value='all';renderList();renderMarkers();const points=filtered().filter(p=>p.lat!==null).map(p=>[p.lat,p.lng]);state.map?.fitBounds(points);}`);
fn('search',`async function search(e){e.preventDefault();const q=$('#search').value.trim();const token=state.searchGate.next();if(!q){$('#search-results').innerHTML='';return;}const coords=q.match(/^\\s*(-?\\d+(?:\\.\\d+)?)\\s*,\\s*(-?\\d+(?:\\.\\d+)?)\\s*$/);if(coords){const lat=Number(coords[1]),lng=Number(coords[2]);if(Math.abs(lat)>90||Math.abs(lng)>180)return toast('위도·경도를 확인하세요.');state.holdRows=false;state.map?.setView([lat,lng],16);parcelForm(null,{lat,lng});return;}const local=state.parcels.filter(p=>(p.name+' '+p.address+' '+p.pnu).includes(q)).map(p=>({name:p.name,id:p.id}));$('#search-results').innerHTML='<p class="muted"><span class="naver-loading"></span>네이버 주소 검색 중…</p>';let remote=[],error='';try{remote=await searchAddress(q);}catch(err){error=err.message;}if(!state.searchGate.current(token))return;state.search=[...local,...remote];$('#search-results').innerHTML=state.search.length?state.search.map((r,i)=>'<button data-result="'+i+'">'+esc(r.name)+(r.id?' · 내 농지':' · 네이버 주소')+' →</button>').join(''):'<p class="muted">'+esc(error||'주소 검색 결과가 없습니다. 더 구체적인 주소·지번을 입력하세요.')+'</p>';}`);
replace("state.map?.setView([r.lat,r.lng],14);toast('검색 위치로 이동했습니다. 지도를 눌러 농지를 등록하세요.');","state.holdRows=false;state.map?.setView([r.lat,r.lng],16);$('#search-results').innerHTML='';toast('네이버 검색 위치로 이동했습니다. 지도를 눌러 농지를 등록하세요.');");
replace("$('#filter').onchange=()=>{renderList();renderMarkers();};","$('#filter').onchange=()=>{state.holdRows=false;renderList();renderMarkers();};");
replace("state.selected=null;$('#detail').hidden=true;await reload();","state.selected=null;state.holdRows=false;$('#detail').hidden=true;await reload();");
replace("await restore({parcels:[],evidence:[]},true);state.selected=null;","await restore({parcels:[],evidence:[]},true);state.holdRows=false;state.hidden.clear();state.selected=null;");
replace("await write('parcels',next);closeModal();await reload();","await write('parcels',next);state.holdRows=false;closeModal();await reload();");
const additions=`
function updateMapTools(){const rows=filtered(),shown=rows.filter(p=>!state.hidden.has(p.id)),all=$('#select-map-all');if(all){all.checked=!!rows.length&&shown.length===rows.length;all.indeterminate=shown.length>0&&shown.length<rows.length;all.disabled=!rows.length;}$('#map-result-count').textContent=rows.length+'건 · 좌표 '+shown.filter(p=>p.lat!==null).length+'개';}
function initWorkspace(){const refresh=()=>{state.holdRows=false;state.bounds=state.map?.bounds||state.bounds;renderList();renderMarkers();};$('#scope').onchange=refresh;$('#map-sort').onchange=refresh;$('#auto-search').onchange=()=>{$('#search-area').hidden=$('#auto-search').checked;if($('#auto-search').checked)refresh();};$('#search-area').onclick=refresh;$('#select-map-all').onchange=e=>{for(const p of filtered())e.target.checked?state.hidden.delete(p.id):state.hidden.add(p.id);renderList();renderMarkers();};document.addEventListener('change',e=>{const id=e.target.dataset.mapCheck;if(id){e.target.checked?state.hidden.delete(id):state.hidden.add(id);renderMarkers();}});$('#zoom-in').onclick=()=>state.map?.zoom(1);$('#zoom-out').onclick=()=>state.map?.zoom(-1);$$('[data-map-type]').forEach(b=>b.onclick=()=>{state.map?.setType(b.dataset.mapType);$$('[data-map-type]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});$('#search-clear').onclick=()=>{$('#search').value='';state.searchGate.cancel();$('#search-results').innerHTML='';$('#search').focus();};const collapse=value=>{document.body.classList.toggle('list-collapsed',value);$('#list-toggle').textContent=value?'목록 열기':'지도 크게';$('#list-toggle').setAttribute('aria-expanded',String(!value));setTimeout(()=>state.map?.invalidateSize(),20);};$('#list-toggle').onclick=()=>collapse(!document.body.classList.contains('list-collapsed'));let start=null;const grip=$('#sheet-grip');grip.onpointerdown=e=>{start=e.clientY;grip.setPointerCapture(e.pointerId);};grip.onpointerup=e=>{if(start!==null&&Math.abs(e.clientY-start)>30)collapse(e.clientY>start);start=null;};grip.onpointercancel=()=>start=null;const moveSearch=()=>{const target=matchMedia('(max-width:1000px)').matches?$('#mobile-search'):$('#desktop-search');target.append($('#search-form'),$('#search-results'));setTimeout(()=>state.map?.invalidateSize(),20);};matchMedia('(max-width:1000px)').addEventListener('change',moveSearch);moveSearch();new MutationObserver(()=>document.body.classList.toggle('detail-open',!$('#detail').hidden)).observe($('#detail'),{attributes:true,attributeFilter:['hidden']});}
`;
replace("try{await reload();}",additions+"\ninitWorkspace();\ntry{await reload();}");
replace("initMap();showView(location.hash.slice(1)||'map');","showView(location.hash.slice(1)||'map');await initMap();");
app=app.replace('키 없이 기본지도·수동등록 모드로 적용했습니다.','네이버 기본지도·수동등록 모드로 적용했습니다.').replace('https://operations.osmfoundation.org/policies/tiles/','https://navermaps.github.io/maps.js.ncp/docs/').replace('OSM 지도 이용정책','네이버 지도 API 안내').replace('https://www.openstreetmap.org/fixthemap','https://map.naver.com/').replace('배경지도 오류 알리기','네이버 지도 열기');
fn('vworldSearch','');app=app.replace(/^const REGIONS=.*$/m,'');
await writeFile('src/app.js',app);
let html=await readFile('index.html','utf8');
html=html.replace(/<link rel="stylesheet" href="https:\/\/unpkg\.com\/leaflet[^>]+>/,'').replace(/<script src="https:\/\/unpkg\.com\/leaflet[^>]+><\/script>/,'');
html=html.replace('<link rel="stylesheet" href="./assets/app.css">','<link rel="stylesheet" href="./assets/app.css"><link rel="stylesheet" href="./assets/naver-ui.css">');
html=html.replace('<form id="search-form"','<div id="desktop-search"><form id="search-form"').replace('<div id="search-results" aria-live="polite"></div>','<div id="search-results" aria-live="polite"></div></div>');
html=html.replace('placeholder="지역·내 농지·위도, 경도 검색"','placeholder="주소·지번·내 농지 검색"').replace('<button type="submit" aria-label="검색">','<button id="search-clear" class="search-clear" type="button" aria-label="검색어 지우기">×</button><button type="submit" aria-label="검색">');
html=html.replace('정확한 주소·지번 검색은 VWorld API 연결 후 이용','네이버 주소 검색 · 지도 목록은 저장한 농지 기준');
html=html.replace('<aside class="sidebar">','<aside class="sidebar"><button id="sheet-grip" class="sheet-grip" aria-label="목록 크기 조절 손잡이" type="button"></button>');
html=html.replace('<div id="parcel-list"></div>','<div class="map-list-tools"><select id="scope" aria-label="목록 범위"><option value="viewport">현재 지도영역</option><option value="all">전체 농지</option></select><select id="map-sort" aria-label="농지 정렬"><option value="recent">최근 등록순</option><option value="status">점검 우선순</option><option value="name">이름순</option><option value="area">면적 큰순</option></select></div><label class="auto-search"><input type="checkbox" id="auto-search" checked> 지도 이동 후 자동 목록 갱신</label><div class="selection-tools"><label><input type="checkbox" id="select-map-all" checked> 지도 모두 표시</label><span id="map-result-count">0건</span></div><div id="parcel-list"></div>');
html=html.replace('<div class="map-label"><span class="live-dot"></span> 실제 배경지도 <span class="divider">|</span> 경계·행정정보 자동판정 없음</div>','<div id="mobile-search" class="map-search-slot"></div><div class="map-label" role="group" aria-label="지도 유형"><button data-map-type="normal" aria-pressed="false">일반지도</button><button data-map-type="hybrid" aria-pressed="true">위성·도로</button><small>NAVER · 위치 참고</small></div><button id="search-area" class="map-research" hidden>이 지도에서 조회</button>');
html=html.replace('<div class="map-actions">','<div class="map-actions"><button id="zoom-in" aria-label="지도 확대">＋</button><button id="zoom-out" aria-label="지도 축소">−</button>');
html=html.replace('<article id="detail"','<div class="map-dock"><button id="list-toggle" aria-expanded="true">지도 크게</button></div><article id="detail"');
html=html.replace('v0.1.0','v0.2.0');await writeFile('index.html',html);
let sw=await readFile('sw.js','utf8');sw=sw.replace('app-v1','app-v2').replace("'./assets/app.css',","'./assets/app.css','./assets/naver-ui.css','./src/naver-map.js','./src/map-utils.js',");await writeFile('sw.js',sw);
for(const file of ['package.json','src/domain.js','scripts/build.mjs']){const t=await readFile(file,'utf8');await writeFile(file,t.replaceAll('0.1.0','0.2.0'));}
let test=await readFile('tests/browser_smoke.py','utf8');test=test.replace("page.wait_for_selector('.leaflet-container',timeout=15000)","page.wait_for_selector('body[data-map-ready=\"true\"]',timeout=20000)");test=test.replace("page.wait_for_selector('img.leaflet-tile-loaded',timeout=20000)","page.wait_for_function(\"Array.from(document.querySelectorAll('#map img')).some(i=>i.naturalWidth>100&&/naver|pstatic/.test(i.src))\",timeout=20000)");test=test.replace("    page.locator('#f-name').fill('검증용 농지')","    page.locator('#f-name').fill('검증용 농지')\n    page.locator('#f-lat').fill('37.3595704')\n    page.locator('#f-lng').fill('127.105399')");
const naverChecks=String.raw`    if LIVE:
        assert page.locator('#map').get_attribute('data-provider')=='naver'
        assert page.evaluate('typeof window.L')=='undefined'
        page.locator('[data-map-type="normal"]').click()
        assert page.locator('#map').get_attribute('data-map-type')=='normal'
        page.locator('[data-map-type="hybrid"]').click()
        page.locator('#search').fill('경기도 성남시 분당구 불정로 6')
        page.locator('#search-form button[type="submit"]').click()
        page.wait_for_selector('#search-results button[data-result]',timeout=15000)
        assert '네이버 주소' in page.locator('#search-results').inner_text()
        page.locator('#search-results button[data-result]').first.click()
        page.locator('#search-clear').click()
`;
test=test.replace("    page.screenshot(path=str(out/'desktop.png'),full_page=True)",naverChecks+"    page.screenshot(path=str(out/'desktop.png'),full_page=True)");
const markerChecks=String.raw`    if LIVE:
        page.wait_for_selector('.naver-pin[data-pin]')
        assert page.locator('.pin-rank').first.inner_text()=='1'
        page.locator('[data-action="close-detail"]').click()
        page.locator('#select-map-all').uncheck()
        assert page.locator('.naver-pin').count()==0
        page.locator('#select-map-all').check()
        page.wait_for_selector('.naver-pin')
        page.locator('.parcel-card').first.click()
`;
test=test.replace("    page.locator('[data-task=\"inheritance\"]').check()",markerChecks+"    page.locator('[data-task=\"inheritance\"]').check()");
test=test.replace("'browserErrors':errors","'browserErrors':errors,'naverMapAndGeocoderChecked':LIVE");
await writeFile('tests/browser_smoke.py',test);
const pkg=JSON.parse(await readFile('package.json','utf8'));pkg.scripts.check+=' && node --check src/naver-map.js && node --check src/map-utils.js';await writeFile('package.json',JSON.stringify(pkg,null,2)+'\n');
let readme=await readFile('README.md','utf8');readme=readme.replace('API 키 없이 작동합니다.','별도 키 입력 없이 기본 설정으로 작동합니다.').replace('Leaflet + OpenStreetMap','네이버 Maps v3 (기본 위성·도로 혼합지도)').replace('unpkg/OSM','네이버 Maps').replace('정확한 지번 검색과 국가 공간정보 레이어는 브라우저용 키가 필요합니다.','주소·지번 검색은 네이버 Geocoder로 전환했습니다. 지적도·농업진흥지역 등 WMS 레이어에는 VWorld 키가 필요합니다.');
readme += '\n## v0.2.0 네이버 지도 전환\n\n사용자 요청에 따라 `softm/homecare-nationwide-care-services-map`의 지도 흐름과 UI를 참고했습니다. 참고 커밋: `263fddd1393cae2fc840d64a3fc80c353c1fcdb3`.\n\n- 네이버 SDK+Geocoder, 기본 HYBRID, 일반지도 전환, 확대/축소/현재위치.\n- 현재 지도영역 자동 조회(저장 농지 기준), 수동 재조회, 전체/현재영역, 정렬, 지도 모두 표시 체크박스.\n- 동일 목록 번호의 상태 마커, 선택 강조, 선택 시 목록 순번 보존, 지도 위치·배율 탭 세션 유지.\n- 모바일 지도 검색창·접이식 목록·하단 상세 패널. 기존 농지/증빙 DB는 변경하지 않았습니다.\n- 참고 저장소의 공개 브라우저 ID를 기본 사용하며 Client Secret은 사용하지 않습니다. Maps Application에 현재 Origin이 허용되어야 하며 같은 ID 사용량을 공유합니다. 네이버 API 실패를 OSM 성공으로 가장하지 않습니다.\n- VWorld WMS는 네이버 GroundOverlay로 표시하며 경계/소유권 공식 판정이 아닙니다.\n';await writeFile('README.md',readme);
console.log('Naver map source migration complete; existing parcel/evidence stores preserved.');
