/** Naver map experience adapted from softm/homecare-nationwide-care-services-map.
 * Pins are user-entered locations, never cadastral boundaries or ownership proof.
 */
import {escapeHtml as esc,STATUS,assess} from './domain.js';
import {DEFAULT_NAVER_KEY,validPoint,createQueryCache,mercatorBounds} from './map-utils.js';
let sdkPromise;
export function loadNaver(key=DEFAULT_NAVER_KEY,onFailure=()=>{}){
 if(window.naver?.maps?.Service)return Promise.resolve(window.naver.maps);
 if(sdkPromise)return sdkPromise;
 sdkPromise=new Promise((resolve,reject)=>{
  const script=document.createElement('script');let poll,finished=false;const start=Date.now();
  const failure=()=>{onFailure('네이버 지도 인증 실패: 현재 사이트 Origin을 Maps Application에 등록하세요.');if(!finished){finished=true;clearTimeout(poll);script.remove();reject(Error('네이버 지도 인증·도메인 설정 확인이 필요합니다.'));}};
  window.navermap_authFailure=failure;
  const ready=()=>{if(finished)return;if(window.naver?.maps?.Service){finished=true;resolve(window.naver.maps);return;}if(Date.now()-start>12000){failure();return;}poll=setTimeout(ready,100);};
  const params=new URLSearchParams({ncpKeyId:key||DEFAULT_NAVER_KEY,submodules:'geocoder'});script.src='https://oapi.map.naver.com/openapi/v3/maps.js?'+params;script.async=true;script.onerror=failure;document.head.append(script);ready();
 }).catch(e=>{sdkPromise=null;throw e;});return sdkPromise;
}
function serviceRequest(method,options){return new Promise((resolve,reject)=>{const s=window.naver?.maps?.Service;if(!s?.[method])return reject(Error('네이버 주소 검색 모듈을 확인하세요.'));let settled=false;const timer=setTimeout(()=>{settled=true;reject(Error('주소 검색 응답이 지연됩니다. 다시 검색하세요.'));},10000);try{s[method](options,(status,response)=>{if(settled)return;settled=true;clearTimeout(timer);if(status!==s.Status.OK)return reject(Error('네이버 주소 검색 오류: 서비스 권한·허용 도메인을 확인하세요.'));resolve(response);});}catch(e){clearTimeout(timer);reject(e);}});}
export const searchAddress=createQueryCache(async query=>{const r=await serviceRequest('geocode',{query,count:8});return (r.v2?.addresses||[]).map(x=>({name:x.jibunAddress||x.roadAddress||query,road:x.roadAddress||'',lat:Number(x.y),lng:Number(x.x)})).filter(validPoint);});
export async function reverseAddress(point){const r=await serviceRequest('reverseGeocode',{coords:new window.naver.maps.LatLng(point.lat,point.lng),orders:'addr,roadaddr'});return r.v2?.address?.jibunAddress||r.v2?.address?.roadAddress||'';}
export class NaverMapController {
 constructor(element,{onPick,onViewport,onGesture,onStatus,getConfig}){this.element=element;this.callbacks={onPick,onViewport,onGesture,onStatus,getConfig};this.markers=new Map();this.overlays=[];this.bounds=null;this.sequence=0;this.suppressUntil=0;this.selected=null;this.lastWms='';this.disposed=false;}
 async init(key){const n=await loadNaver(key,message=>{document.body.dataset.mapReady='false';this.callbacks.onStatus(message);});let saved;try{saved=JSON.parse(sessionStorage.getItem('farmland-map-view-v2')||'null');}catch{}const center=validPoint(saved)?saved:{lat:36.35,lng:127.8};this.raw=new n.Map(this.element,{center:new n.LatLng(center.lat,center.lng),zoom:saved?.zoom>=7&&saved.zoom<=19?saved.zoom:7,minZoom:7,maxZoom:19,mapTypeId:saved?.type==='normal'?n.MapTypeId.NORMAL:n.MapTypeId.HYBRID,zoomControl:false,scrollWheel:true,pinchZoom:true,draggable:true,zoomDuration:180});
  this.handlers=[n.Event.addListener(this.raw,'dragstart',()=>{this.suppressUntil=0;this.callbacks.onGesture();}),n.Event.addListener(this.raw,'zoom_changed',()=>this.schedule()),n.Event.addListener(this.raw,'idle',()=>this.schedule()),n.Event.addListener(this.raw,'click',e=>this.pick(e.coord))];
  this.resizeObserver=new ResizeObserver(()=>this.invalidateSize());this.resizeObserver.observe(this.element);document.body.dataset.mapReady='true';this.element.dataset.provider='naver';this.element.dataset.mapType=this.raw.getMapTypeId()==='normal'?'normal':'hybrid';this.element.setAttribute('aria-label','네이버 농지 지도');this.schedule();return this;
 }
 schedule(){clearTimeout(this.timer);this.timer=setTimeout(()=>{if(!this.raw||this.disposed)return;const box=this.raw.getBounds();if(!box)return;const sw=box.getSW(),ne=box.getNE();this.bounds={south:sw.lat(),west:sw.lng(),north:ne.lat(),east:ne.lng()};const c=this.getCenter();try{sessionStorage.setItem('farmland-map-view-v2',JSON.stringify({...c,zoom:this.getZoom(),type:this.raw.getMapTypeId()==='normal'?'normal':'hybrid'}));}catch{}if(Date.now()>=this.suppressUntil)this.callbacks.onViewport(this.bounds);this.updateLabels();this.updateOverlays();},350);}
 getCenter(){if(!this.raw)return {lat:36.35,lng:127.8};const p=this.raw.getCenter();return {lat:p.lat(),lng:p.lng()};}
 getZoom(){return this.raw?.getZoom()??7;}
 setView(coords,zoom=15){if(!this.raw)return this;this.suppressUntil=0;this.raw.setCenter(new naver.maps.LatLng(coords[0],coords[1]));this.raw.setZoom(Math.min(19,Math.max(7,zoom)));return this;}
 invalidateSize(){if(!this.raw||this.disposed)return;const c=this.raw.getCenter();naver.maps.Event.trigger(this.raw,'resize');this.raw.setCenter(c);}
 fitBounds(points){if(!this.raw)return;if(!points.length)return this.setView([36.35,127.8],7);if(points.length===1)return this.setView(points[0],15);const b=new naver.maps.LatLngBounds();points.forEach(([lat,lng])=>b.extend(new naver.maps.LatLng(lat,lng)));this.raw.fitBounds(b,{top:100,right:65,bottom:80,left:65});}
 zoom(delta){if(!this.raw)return;this.suppressUntil=0;this.callbacks.onGesture();this.raw.setZoom(Math.max(7,Math.min(19,this.getZoom()+delta)),true);}
 setType(type){if(!this.raw)return;this.element.dataset.mapType=type;this.raw.setMapTypeId(type==='normal'?naver.maps.MapTypeId.NORMAL:naver.maps.MapTypeId.HYBRID);this.schedule();}
 focus(id){const m=this.markers.get(id);if(!m)return;this.suppressUntil=Date.now()+1600;this.selected=id;const pos=m.getPosition();this.raw.setCenter(pos);if(this.getZoom()<15)this.raw.setZoom(15);requestAnimationFrame(()=>{if(this.element.clientWidth>700&&document.querySelector('#detail:not([hidden])')){const projection=this.raw.getProjection(),p=projection.fromCoordToOffset(pos);this.raw.setCenter(projection.fromOffsetToCoord(new naver.maps.Point(p.x+185,p.y)));}this.highlight(id);});}
 highlight(id){this.selected=id;for(const [pid,m]of this.markers){m.setZIndex(pid===id?2000:10);const el=m.getElement?.();el?.querySelector('.naver-pin')?.classList.toggle('selected',pid===id);if(pid===id){const pin=el?.querySelector('.naver-pin');pin?.classList.remove('blink');requestAnimationFrame(()=>pin?.classList.add('blink'));}}}
 render(rows,hidden=new Set(),selected=null){if(!this.raw)return;const wanted=new Set();rows.forEach((p,index)=>{if(!validPoint(p)||hidden.has(p.id))return;wanted.add(p.id);const a=assess(p),position=new naver.maps.LatLng(p.lat,p.lng);let m=this.markers.get(p.id);const content=`<div class="naver-pin ${a.status} ${p.id===selected?'selected':''}" data-pin="${esc(p.id)}"><span class="pin-state">${STATUS[a.status].title}</span><b class="pin-rank">${index+1}</b><span class="pin-name">${esc(p.name)}</span></div>`;if(!m){m=new naver.maps.Marker({map:this.raw,position,title:p.name,icon:{content,anchor:new naver.maps.Point(36,44)},zIndex:p.id===selected?2000:10});m._listener=naver.maps.Event.addListener(m,'click',()=>this.onSelect?.(p.id));this.markers.set(p.id,m);}else{m.setPosition(position);m.setIcon({content,anchor:new naver.maps.Point(36,44)});m.setMap(this.raw);}});for(const [id,m]of this.markers)if(!wanted.has(id)){naver.maps.Event.removeListener(m._listener);m.setMap(null);this.markers.delete(id);}this.selected=selected;this.updateLabels();}
 updateLabels(){const used=[];for(const [id,m]of this.markers){const el=m.getElement?.(),name=el?.querySelector('.pin-name');if(!name)continue;name.hidden=this.getZoom()<13&&id!==this.selected;if(name.hidden)continue;const r=name.getBoundingClientRect();if(id!==this.selected&&used.some(b=>r.left<b.right+6&&r.right+6>b.left&&r.top<b.bottom+6&&r.bottom+6>b.top))name.hidden=true;else used.push(r);}}
 async pick(coord){const point={lat:coord.lat(),lng:coord.lng()};this.closePopup();const seq=++this.sequence;const host=document.createElement('div');host.className='pick-location';host.innerHTML=`<strong>선택한 위치</strong><p>${point.lat.toFixed(6)}, ${point.lng.toFixed(6)}</p><p class="pick-address">주소 확인 중…</p><small>위치 참고 · 지적경계/소유권 미확인</small>`;const b=document.createElement('button');b.className='primary';b.textContent='이 위치에 농지 등록';b.onclick=()=>{this.closePopup();this.callbacks.onPick(point);};host.append(b);this.popup=new naver.maps.InfoWindow({content:host,maxWidth:290,borderWidth:0,backgroundColor:'#fff',disableAnchor:false});this.popup.open(this.raw,coord);try{const address=await reverseAddress(point);if(seq===this.sequence){point.address=address;host.querySelector('.pick-address').textContent=address||'주소 결과 없음 · 직접 입력 가능';}}catch{if(seq===this.sequence)host.querySelector('.pick-address').textContent='주소 조회 불가 · 좌표로 등록 가능';}}
 closePopup(){this.popup?.close();this.popup=null;this.sequence++;}
 updateOverlays(force=false){if(!this.raw||!this.bounds)return;const c=this.callbacks.getConfig();const layers=[c.cadastre&&this.getZoom()>=15?'lp_pa_cbnd_bubun,lp_pa_cbnd_bonbun':'',c.agri?'lt_c_agrixue101':'',c.unfavorable?'lt_c_agrixue102':''].filter(Boolean);const token=JSON.stringify([this.bounds,layers,c.vworldKey,c.vworldDomain]);if(!force&&token===this.lastWms)return;this.lastWms=token;this.overlays.forEach(x=>x.setMap(null));this.overlays=[];if(!c.vworldKey||!layers.length)return;const bounds=this.bounds;const params=new URLSearchParams({service:'WMS',request:'GetMap',version:'1.3.0',crs:'EPSG:3857',bbox:mercatorBounds(bounds).join(','),width:String(Math.min(1400,this.element.clientWidth)),height:String(Math.min(1000,this.element.clientHeight)),layers:layers.join(','),styles:layers.join(','),format:'image/png',transparent:'true',key:c.vworldKey,domain:c.vworldDomain});const url='https://api.vworld.kr/req/wms?'+params;const image=new Image();image.onload=()=>{if(token!==this.lastWms||this.disposed)return;const overlay=new naver.maps.GroundOverlay(url,new naver.maps.LatLngBounds(new naver.maps.LatLng(bounds.south,bounds.west),new naver.maps.LatLng(bounds.north,bounds.east)),{opacity:.6,clickable:false});overlay.setMap(this.raw);this.overlays.push(overlay);};image.onerror=()=>{if(token===this.lastWms)this.callbacks.onStatus('VWorld 영상 조회 실패: 키·서비스 권한 확인이 필요합니다.');};image.src=url;}
 dispose(){this.disposed=true;clearTimeout(this.timer);this.resizeObserver?.disconnect();this.closePopup();this.markers.forEach(m=>{naver.maps.Event.removeListener(m._listener);m.setMap(null);});this.overlays.forEach(o=>o.setMap(null));this.handlers?.forEach(h=>naver.maps.Event.removeListener(h));this.raw?.destroy();}
}
